spring:
  application:
    name: arlian-site

  # Web
  thymeleaf:
    mode: HTML

  # Hibernate
  jpa:
    properties:
      hibernate:
        default_schema: arlian_org
        jdbc:
          batch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

    # JPA / Hibernate
    # Don't allow opening new transactions in the view. Work properly (use a DAO or Service from the Controller).
    open-in-view: false

  datasource:
    # Hikari
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1500000
      connection-timeout: 5000

    # Connection
    driver-class-name: org.postgresql.Driver


  # JMX
  jmx:
    enabled: true

  # request sizes, e.g. for uploading pictures
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # Flyway
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.1.0
    schemas: arlian_org

  # OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 731142352505-lbrn4va4810s59ogrtptkvtbcjabpkcm.apps.googleusercontent.com
            client-secret: BO42uXc447rcDLl4_fbWd4Yd

  # Caching
  web:
    resources:
      cache:
        period: 2592000s

server:
  servlet:
    context-path: /